
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/PicSingularDatabase?characterEncoding=utf-8&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}
    connect-timeout: 5000
    jedis:
      pool:
        max-idle: 10
        max-wait: -1
        min-idle: 5

server:
  port: ${SERVER_PORT}
  error:
    include-message: ALWAYS
    include-stacktrace: NEVER
